Importing tax rates from xero to fyle
fylein/fyle-xero-api pull request #102
Opened 2022-03-29 13:06 UTC by harshithaputtaswamy

2022-03-30 05:16 UTC, Shwetabhk requested changes

2022-03-30 05:16 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +        platform_connection.connection.v1.admin.tax_groups.post(payload)
@harshithaputtaswamy we don't need to do this in a loop
We also have a bulk post function in the platform connector, check qbo-api for example

2022-03-30 05:16 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +                    'percentage': round((xero_attribute.detail['tax_rate']/100), 2)
@NileshPant1999 please review this once

2022-03-30 05:16 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +            source_field='TAX_GROUP', workspace_id=workspace_id
Also, add `destination_type='TAX_CODE'`

2022-03-30 05:16 UTC, Shwetabhk commented on apps/mappings/views.py
> +        # general_mapping_payload['default_tax_code_name'] = "Tax on Goodss @8.125%"
remove this

2022-03-30 05:16 UTC, Shwetabhk commented on apps/workspaces/models.py
> +    cluster_domain = models.CharField(max_length=255, help_text='Cluster domain', null=True)
@NileshPant1999 @ashwin1111 We would need to fill cluster domains in db?

2022-03-30 05:16 UTC, Shwetabhk commented on apps/xero/models.py
>      )
Also need to handle bank transactions similar to bills

2022-03-30 05:16 UTC, Shwetabhk commented on apps/workspaces/views.py
> +from asyncio.log import logger
remove import too when you remove logger

2022-03-30 05:16 UTC, Shwetabhk commented on apps/workspaces/utils.py
> +logger = logging.getLogger(__name__)
is logger used anywhere?

2022-03-30 05:21 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +    :return: Fyle Cost Centers Payload
@harshithaputtaswamy please change cost center to taxes.

2022-03-30 05:21 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +            schedule.delete()
new line

2022-03-30 05:25 UTC, NileshPant1999 commented on apps/xero/utils.py
> +                'UnitAmount': line.amount, #TODO: line.amount - line.tax_amount if line.tax_code else self.get_tax_inclusive_amount(line.amount, general_mappings.default_tax_code_id),
please fix this

2022-03-30 05:28 UTC, Shwetabhk commented on apps/workspaces/models.py
> +    cluster_domain = models.CharField(max_length=255, help_text='Cluster domain', null=True)
@NileshPant1999 Won't we already have cluster domain in fyle credentials table?

2022-03-30 05:30 UTC, NileshPant1999 commented on apps/workspaces/models.py
> +    cluster_domain = models.CharField(max_length=255, help_text='Cluster domain', null=True)
@Shwetabhk we don't need this, we already have cluster domain in fyle credentials table

2022-03-30 05:38 UTC, NileshPant1999 commented on apps/xero/utils.py
> +
@harshithaputtaswamy i think this is qbo specific not needed in xero, please check the doc to confirm

2022-03-30 05:39 UTC, NileshPant1999 commented on apps/xero/views.py
> +from apps.workspaces.serializers import WorkspaceSerializer, XeroCredentialSerializer
no usage of this import

2022-03-31 10:56 UTC, Shwetabhk commented on apps/fyle/tasks.py
> +                filter_credit_expenses = True
```suggestion
                filter_credit_expenses=True
```

2022-03-31 10:57 UTC, Shwetabhk commented on apps/fyle/tasks.py
> +                filter_credit_expenses = True
@ashwin1111 please check if this change is required?

2022-03-31 10:57 UTC, Shwetabhk commented on apps/mappings/signals.py
> +                        upload_attributes_to_fyle, schedule_tax_groups_creation
this is imported but not used

2022-03-31 11:00 UTC, Shwetabhk commented on apps/mappings/views.py
> +from asyncio.log import logger
Remove import

2022-03-31 11:00 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +                filter_credit_expenses = True
Why is this boolean introduced? I don't see any reference in the code. Am I missing something?

2022-03-31 11:01 UTC, Shwetabhk commented on apps/xero/urls.py
> +        ReimburseXeroPaymentsView, SyncXeroDimensionView, RefreshXeroDimensionView, ExportsTriggerView, TaxCodeView, DestinationAttributesView
```suggestion
        ReimburseXeroPaymentsView, SyncXeroDimensionView, RefreshXeroDimensionView, \
            ExportsTriggerView, TaxCodeView, DestinationAttributesView
```

2022-03-31 11:01 UTC, Shwetabhk commented on apps/xero/utils.py
> +        tax_attribute = DestinationAttribute.objects.filter(destination_id=default_tax_code_id, attribute_type='TAX_CODE',workspace_id=self.workspace_id).first()
Line is too long

2022-03-31 11:02 UTC, Shwetabhk commented on apps/xero/utils.py
> +        tax_attribute = DestinationAttribute.objects.filter(destination_id=default_tax_code_id, attribute_type='TAX_CODE',workspace_id=self.workspace_id).first()
```suggestion
        tax_attribute = DestinationAttribute.objects.filter(
            destination_id=default_tax_code_id, 
            attribute_type='TAX_CODE',
            workspace_id=self.workspace_id
        ).first()
```

2022-03-31 11:10 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +                filter_credit_expenses = True
This should be true

2022-04-05 06:09 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        mapping_setting = MappingSetting.objects.get(
We don't need this query, can directly add `TAX_CODE` for `destination_field` in `sync_xero_attributes()`
Since we know what the destination field gonna be

2022-04-05 06:09 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    import_tax_codes = True
remove this

2022-04-05 06:10 UTC, ashwin1111 commented on apps/mappings/views.py
> +            logger.error("Error while fetching company information")
Use single quotes for consistency across code base

2022-04-05 06:12 UTC, ashwin1111 commented on apps/mappings/views.py
> +            company_info = xero_connector.get_organisations()[0]
This operation should happen in the XeroCredentials creation part

2022-04-05 06:14 UTC, ashwin1111 commented on apps/mappings/views.py
> +            company_info = xero_connector.get_organisations()[0]
I see that we are doing it there too, any reasons why we are doing same at 2 places?

2022-04-05 06:14 UTC, ashwin1111 commented on apps/xero/models.py
> +def get_tax_code_id_or_none(expense_group: ExpenseGroup, lineitem: Expense = None):
need not assign it to None

2022-04-05 06:16 UTC, ashwin1111 commented on apps/xero/utils.py
> +            'LineAmountTypes': 'Exclusive',
Will this have any impact on non tax org?

2022-04-05 06:17 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    platform_connection.connection.v1beta.admin.tax_groups.post_bulk(fyle_payload)
please use platform connector library's method for bulk post

2022-04-05 12:47 UTC, harshithaputtaswamy commented on apps/mappings/views.py
> +            company_info = xero_connector.get_organisations()[0]
Initially when xero is connected tenent id wont be there and it is needed to get the org details, so had to make a call after tenent is added

2022-04-06 07:31 UTC, ashwin1111 approved these changes

2022-04-06 07:31 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        # mapping_setting = MappingSetting.objects.get(
remove this dead code

2022-04-06 10:49 UTC, Shwetabhk approved these changes

2022-04-06 10:50 UTC, merged