workspace-module changes
fylein/fyle-xero-api pull request #175
Opened 2022-10-14 12:03 UTC by labhvam5

2022-10-18 07:41 UTC, ashwin1111 requested changes

2022-10-18 07:41 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +                last_paid_at=last_synced_at if expense_group_settings.ccc_expense_state == 'PAID' else None
this is to maintain stuffs for old app as well as new app

2022-10-18 07:41 UTC, ashwin1111 commented on apps/workspaces/views.py
> +            org_currency = fyle_user['data']['org']['currency']
same

2022-10-19 07:44 UTC, labhvam5 commented on apps/workspaces/models.py
> +    fyle_currency = models.CharField(max_length=5, help_text='Fyle Currency', null=True)
No we need to do it along with these changes only .

2022-10-19 07:46 UTC, labhvam5 commented on apps/workspaces/apis/export_settings/serializers.py
> +            expense_group_settings['ccc_export_date_type'] = 'current_date'
yes .

2022-10-20 13:22 UTC, ashwin1111 commented on scripts/python/001_fill_xero_and_fyle_currency.py
> +        platform = PlatformConnector(fyle_credentials)
Do this in a try catch block, expired tokens shouldn't affect the script

2022-10-20 13:22 UTC, ashwin1111 commented on scripts/python/001_fill_xero_and_fyle_currency.py
> +        xero_connector = XeroConnector(xero_credentials, workspace_id=workspace.id)
Do this in a try catch block, expired tokens shouldn't affect the script

2022-10-20 13:22 UTC, ashwin1111 commented on scripts/python/001_fill_xero_and_fyle_currency.py
> +workspaces = Workspace.objects.filter(Q(fyle_currency=None) | Q(xero_currency=None)).all()
Write an sql script to fill dummy currency - "USD" for all demo and test orgs. We can run that first and then run this script.

2022-10-20 13:53 UTC, ashwin1111 commented on sql/scripts/011-fill-xero-and-fyle-currency-demo-orgs.sql
> +  id in (
id not in :P

2022-10-20 13:54 UTC, ashwin1111 approved these changes

2022-10-21 06:37 UTC, merged