catch xero credential error while uploading categories
fylein/fyle-xero-api pull request #61
Opened 2021-07-27 10:26 UTC by NileshPant1999

2021-07-27 11:06 UTC, Sravanksk approved these changes

2021-07-27 14:28 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        xero_credentials: XeroCredentials = XeroCredentials.objects.get(workspace_id=workspace_id)
Can you check other places too and fix in one go? Auto Map Employees, etc

2021-07-28 07:00 UTC, ashwin1111 requested changes

2021-07-28 07:00 UTC, ashwin1111 commented on apps/xero/tasks.py
> +    try:
This function is already called in a try block in the parent function, not needed here. Please check elsewhere and remove it off and assign the PR back.

2021-07-30 14:52 UTC, ashwin1111 requested changes
edit: resolved;

2021-07-30 14:57 UTC, ashwin1111 approved these changes

2021-08-02 17:54 UTC, merged